x-pi-volumes: &pi-volumes
  - pi-logs:/app/logs
  # - {path-to-env-file}:/app/env-staging.ini
  # - {path-to-fact-detection-model-file}:/app/worker/insightface/save_model/models/face_detection/scrfd_10g_bnkps.onnx
  # - {path-to-fact-recognition-model-file}:/app/worker/facenet_recognition/save_model/svm.sav
  # - {path-to-fact-recognition-lable-file}:/app/worker/facenet_recognition/save_model/svm.sav

  - ./backend/app/env-staging.ini:/app/env-staging.ini
  - ./backend/app/worker/insightface/save_model/models/face_detection/scrfd_10g_bnkps.onnx:/app/worker/insightface/save_model/models/face_detection/scrfd_10g_bnkps.onnx
  - ./backend/app/worker/facenet_recognition/save_model/classes_label.json:/app/worker/facenet_recognition/save_model/classes_label.json
  - ./backend/app/worker/facenet_recognition/save_model/svm.sav:/app/worker/facenet_recognition/save_model/svm.sav


x-networks: &pi-networks
  - pi-net

version: '3.8'

services:
  api:
    container_name: pi-api-prod
    image: duynguyenngoc/pi-ai:backend
    restart: unless-stopped
    volumes: *pi-volumes
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8081 --reload"
    networks: *pi-networks
    ports: 
      - "8081:8081"
networks:
  pi-net:

volumes:
  pi-logs: